### ISSUE TITLE
mulaw Flow

### ISSUE THREAD

**Issue by eng1n88r** [ex3ndr/super-hardware#1]
Hey, I think there is a typo: 
https://github.com/ex3ndr/super-hardware/blob/4d99b2bd364a503c23737ce046d2847f10754716/firmware/nrf52840_nordic/client.py#L76

`pcm16_samples` should be instead of `audio_data`:
```c
 audio_data = np.frombuffer(pcm16_samples , dtype=np.int16)
```

**Comment by ex3ndr** [comment]
Oh man thanks! I have fixed mulaw!!
